"""empty message

Revision ID: 3f7aa48eaf3a
Revises: 
Create Date: 2022-07-11 16:08:00.002287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7aa48eaf3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('admin_impersonate_uid', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('new_name_two', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('principal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('NOT(user_id IS NULL AND group_id IS NULL)'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('process_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_model_identifier', sa.String(length=50), nullable=False),
    sa.Column('process_group_identifier', sa.String(length=50), nullable=False),
    sa.Column('process_initiator_id', sa.Integer(), nullable=False),
    sa.Column('bpmn_json', sa.JSON(), nullable=True),
    sa.Column('start_in_seconds', sa.Integer(), nullable=True),
    sa.Column('end_in_seconds', sa.Integer(), nullable=True),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['process_initiator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_instance_process_group_identifier'), 'process_instance', ['process_group_identifier'], unique=False)
    op.create_index(op.f('ix_process_instance_process_model_identifier'), 'process_instance', ['process_model_identifier'], unique=False)
    op.create_table('process_instance_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('process_model_identifier', sa.String(length=50), nullable=False),
    sa.Column('process_group_identifier', sa.String(length=50), nullable=False),
    sa.Column('report_metadata', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_group_identifier', 'process_model_identifier', 'identifier', name='process_instance_report_unique')
    )
    op.create_index(op.f('ix_process_instance_report_identifier'), 'process_instance_report', ['identifier'], unique=False)
    op.create_index(op.f('ix_process_instance_report_process_group_identifier'), 'process_instance_report', ['process_group_identifier'], unique=False)
    op.create_index(op.f('ix_process_instance_report_process_model_identifier'), 'process_instance_report', ['process_model_identifier'], unique=False)
    op.create_table('user_group_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='user_group_assignment_unique')
    )
    op.create_table('active_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spiffworkflow_task_id', sa.String(length=50), nullable=False),
    sa.Column('process_instance_id', sa.Integer(), nullable=False),
    sa.Column('assigned_principal_id', sa.Integer(), nullable=True),
    sa.Column('spiffworkflow_task_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('form_file_name', sa.String(length=50), nullable=True),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_principal_id'], ['principal.id'], ),
    sa.ForeignKeyConstraint(['process_instance_id'], ['process_instance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spiffworkflow_task_id', 'process_instance_id', name='active_task_unique')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('process_instance_id', sa.Integer(), nullable=True),
    sa.Column('task_spec', sa.String(length=50), nullable=True),
    sa.Column('irb_doc_code', sa.String(length=50), nullable=False),
    sa.Column('md5_hash', sa.String(length=50), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('user_uid', sa.String(length=50), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['process_instance_id'], ['process_instance.id'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('process_instance_id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('task_name', sa.String(length=50), nullable=True),
    sa.Column('task_title', sa.String(length=50), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('task_state', sa.String(length=50), nullable=True),
    sa.Column('task_lane', sa.String(length=50), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('mi_type', sa.String(length=50), nullable=True),
    sa.Column('mi_count', sa.Integer(), nullable=True),
    sa.Column('mi_index', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['process_instance_id'], ['process_instance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at_in_seconds', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('process_instance_id', sa.Integer(), nullable=True),
    sa.Column('task_spec', sa.String(length=50), nullable=True),
    sa.Column('spec_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_store')
    op.drop_table('task_event')
    op.drop_table('file')
    op.drop_table('active_task')
    op.drop_table('user_group_assignment')
    op.drop_index(op.f('ix_process_instance_report_process_model_identifier'), table_name='process_instance_report')
    op.drop_index(op.f('ix_process_instance_report_process_group_identifier'), table_name='process_instance_report')
    op.drop_index(op.f('ix_process_instance_report_identifier'), table_name='process_instance_report')
    op.drop_table('process_instance_report')
    op.drop_index(op.f('ix_process_instance_process_model_identifier'), table_name='process_instance')
    op.drop_index(op.f('ix_process_instance_process_group_identifier'), table_name='process_instance')
    op.drop_table('process_instance')
    op.drop_table('principal')
    op.drop_table('user')
    op.drop_table('group')
    op.drop_table('admin_session')
    # ### end Alembic commands ###
